language: python
python:
  - 2.7
env:
  - BUILD_TYPE="Release"
  
before_install:
  - sudo apt-get update
  - sudo apt-get install gfortran
  # Print NumPy version that is already installed by Travis CI:
  - python -c "import numpy; print numpy.__version__"
  - git clone --branch=master --depth=100 --quiet git://github.com/clawpack/clawpack
  - cd clawpack
  - python setup.py symlink-only
  # Grab latest versions of linked repositories
  - for repos in amrclaw clawutil riemann ; do cd $repos ; git pull ; git status ; cd ../ ; done
  - rm -rf geoclaw
  - ln -s ../ geoclaw
  
install:
  - export PYTHONPATH=${PWD}:$PYTHONPATH
  - export CLAW=${PWD}
  - export FC=gfortran
  - cd geoclaw
  
before_script:
  # Print CPU info for debugging purposes:
  - cat /proc/cpuinfo
  - gfortran -v
  - /usr/bin/f95 -v
  - echo "PYTHONPATH="$PYTHONPATH
  - echo "CLAW="$CLAW
  - echo "FC="$FC
  
script:
  - cd $CLAW/geoclaw/
  - nosetests
  - for failed_test_path in *_output ; do cat $failed_test_path/run_output.txt ; cat $failed_test_path/error_output.txt ; done
  - cat src/2d/shallow/filval.f90
  - cat $CLAW/amrclaw/src/2d/amr_module.f90
  
notifications:
  email: false
